### ISSUE TITLE
Configuration: remove Fairwinds Insights suggestion during Polaris audit command

### ISSUE THREAD

**Issue by Nezteb** [FairwindsOps/polaris#1011]
**Is your feature request related to a problem? Please describe.**

I find it odd that every time I run `polaris audit` I see a message at the end suggesting that I re-run the command with the `--upload-insights` flag:

```
❯ polaris audit --audit-path . --only-show-failed-tests true --format=pretty
Polaris audited Path . at 2023-10-29T12:34:36-07:00
    Nodes: 0 | Namespaces: 1 | Controllers: 0
    Final score: 100



🚀 Upload your Polaris findings to Fairwinds Insights to see remediation advice, add teammates, integrate with Slack or Jira, and more:

❯ polaris audit --audit-path . --only-show-failed-tests true --format=pretty --upload-insights --cluster-name=my-cluster

```

**Describe the solution you'd like**

The line is printed here, and it seems like it is printed every single time `polaris audit` is run without the `--upload-insights` flag: https://github.com/FairwindsOps/polaris/blob/97687761a78388a3d00ad875601a19f48a0999ae/cmd/polaris/audit.go#L184

I'd prefer that this is never printed, but I'd accept at least a configuration setting for "turn off Fairwinds Insights suggestion" that can be set to "true".

**Describe alternatives you've considered**

Some alternatives are:
- I give up and just accept the presence of the message.
- I write a quick wrapper script/alias that will remove the output from all calls to `polaris audit`.

**Additional context**

I understand that the Fairwinds team is advertising their paid services using their open-source tool. I just prefer removing all non-essential output and figured I'd make the suggestion. 😅

**Comment by jpelletier1** [comment]
Hi @Nezteb sorry for the delay and thanks for your feedback. I will discuss this with our product team. Agree we could add a flag here in the future.

**Comment by jpelletier1** [comment]
Hi @Nezteb - fyi, our engineers added a `--quiet` option to the CLI. This will suppress the banner. Thanks for the feedback and thanks to @jslivka for the PR!
