### ISSUE TITLE
Unable to Access Polaris Dashboard

### ISSUE THREAD

**Issue by chaitu577** [FairwindsOps/polaris#1016]
### What happened?

I've deployed the Docker using the documentation listed here - https://polaris.docs.fairwinds.com/dashboard/#installation

docker run -d -p8080:8080 -v ~/.kube/config:/opt/app/config:ro  quay.io/fairwinds/polaris:1.2 polaris dashboard --kubeconfig /opt/app/config

### What did you expect to happen?

I'm unable to view the dashboard, it says the "This site can’t be reached", however I'm able to access other dockers on the same port. (**Note**: When testing, I've stopped all the existing docker containers on 8080 port.)

### How can we reproduce this?

NA

### Version

NA

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Are there any logs in the container

**Comment by sudermanjr** [comment]
Also, that version of Polaris is extremely out of date. Please try `us-docker.pkg.dev/fairwinds-ops/oss/polaris:8.5`

**Comment by EsDmitrii** [comment]
same here
no relevant logs from dashboard pod
tried helm with port-forward, tried helm with ingress installation
nginx says 
```10.5.25.48 - - [23/Jan/2024:09:52:31 +0000] "GET / HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 463 1.271 [infra-polaris-polaris-dashboard-80] [] 10.0.1.68:8080 0 1.271 - e6ffb62eda11992bd9ed4de308890137```
when I set 
```
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
      nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
      nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
      nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
      nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
```
nginx says 
```
10.5.25.48 - - [23/Jan/2024:09:53:26 +0000] "GET / HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 17 0.069 [infra-polaris-polaris-dashboard-80] [] 10.0.1.68:8080, 10.0.1.231:8080, 10.0.1.68:8080 0, 0, 0 0.002, 0.066, 0.001 502, 502, 502 b594ace0ce4d27af15615b9ffb6d3b84
2024/01/23 09:53:26 [error] 4068#4068: *29242225 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 10.5.25.48, server: polaris.my.awesome.domain, request: "GET /favicon.ico HTTP/2.0", upstream: "https://10.0.1.231:8080/favicon.ico", host: "polaris.my.awesome.domain", referrer: "https://polaris.my.awesome.domain/"
2024/01/23 09:53:26 [error] 4068#4068: *29242225 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 10.5.25.48, server: polaris.my.awesome.domain, request: "GET /favicon.ico HTTP/2.0", upstream: "https://10.0.1.68:8080/favicon.ico", host: "polaris.my.awesome.domain", referrer: "https://polaris.my.awesome.domain/"
2024/01/23 09:53:26 [error] 4068#4068: *29242225 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 10.5.25.48, server: polaris.my.awesome.domain, request: "GET /favicon.ico HTTP/2.0", upstream: "https://10.0.1.231:8080/favicon.ico", host: "polaris.my.awesome.domain", referrer: "https://polaris.my.awesome.domain/"
```
