### ISSUE TITLE
Validate more resources than deployments

### ISSUE THREAD

**Issue by robscott** [FairwindsOps/polaris#107]
As referenced in our [roadmap](https://github.com/reactiveops/polaris/blob/master/ROADMAP.md#new-controller-types), we want to add support for a variety of additional resources, starting with those that act as parent resources such as pods, including:

- StatefulSet
- DaemonSet
- Job
- CronJob
- ReplicaSet

**Comment by marcecaro** [comment]
What about ReplicaControllers? I know that it is getting replaced by deployments, but it is still very used.

**Comment by endzyme** [comment]
@marcecaro sure thing - I can add that to #166

**Comment by bobby-brennan** [comment]
Implemented in #166
