### ISSUE TITLE
Search and filter namespace

### ISSUE THREAD

**Issue by YuKitAs** [FairwindsOps/polaris#123]
Hello,

I think it would be helpful to build a search input field to filter out one or more specific namespaces with statistics, when you only want to focus on these.

**Comment by bobby-brennan** [comment]
That's a great idea!

To make sure I understand - do you want to view the score for a single namespace, or do you want statistics for a group of namespaces?

**Comment by YuKitAs** [comment]
Hi, I'd go for viewing the spec status for a single namespace. 
The possibility for viewing a group of namespaces e.g. based on naming patterns would just be a plus ;)

**Comment by fust** [comment]
+1

> The possibility for viewing a group of namespaces e.g. based on naming patterns would just be a plus ;)
That would be awesome to have.
