### ISSUE TITLE
Issue with runAsNonRoot

### ISSUE THREAD

**Issue by jclarksnps** [FairwindsOps/polaris#146]
Not entirely sure that your check for runAsNonRoot is working, or we mis-understand exactly what it's checking.  We have a pod running which is set at the pod level as below, yet reactive is still saying it shouldn't run as root... which it isn't.  Since the securityContext at the container level is only for overriding what is set at the pod level I hope that being set at the pod level is enough.  Any ideas?

securityContext:
        runAsNonRoot: true
        runAsUser: 5000

**Comment by endzyme** [comment]
Thanks @jclarksnps - after looking into this, it does look to be a bug. I have been able reproduce locally. I think the missing context here is that the securityContext is not set on the Container but it is set at the pod level. This is innate kube logic which is missing from `polaris`. I can file this as a bug and we'll look at fixing this up in the validation logic. Thanks for the note!!

**Comment by jclarksnps** [comment]
Thanks!

**Comment by endzyme** [comment]
#149 Linking

**Comment by jclarksnps** [comment]
Thanks for fixing this, any eta on a release?

**Comment by endzyme** [comment]
Hi @jclarksnps - I'll get back to you shortly on the timing :smiley: - Thanks again!

**Comment by endzyme** [comment]
@jclarksnps - I am planning on cutting a release tomorrow if that works for you! :)

**Comment by jclarksnps** [comment]
Thanks! Yep, we'll deploy and check it out.

**Comment by endzyme** [comment]
https://github.com/reactiveops/polaris/releases/tag/0.2.1 -- all set 

thanks for your patience!
