### ISSUE TITLE
output-format flag isn't working

### ISSUE THREAD

**Issue by kimschles** [FairwindsOps/polaris#167]
I've tried running `polaris --audit --output-format score` and `polaris --audit --output-format yaml > report.yaml` from the command line, and I'm seeing this error: 
`flag provided but not defined: -output-format` 

The commands work when I run the commands using the `main.go` file.
`go run main.go --audit --output-format score` 
`go run main.go --audit --output-format yaml > report.yaml`

**Comment by bobby-brennan** [comment]
What do you see when you run `polaris --version`?

Do you know how you installed it?

**Comment by kimschles** [comment]
I was on Polaris version 0.1.5. I just upgraded to 0.3.0 and it's working. Thank you.
