### ISSUE TITLE
Add ability to run dashboard using an audit stored as JSON/YAML

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/polaris#183]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
We'd like to be able to save an audit as JSON/YAML, and run the dashboard using that file

**Describe alternatives you've considered**

**Additional context**

**Comment by rbounds** [comment]
Why not just run `./polaris --audit` as a k8s kind: `CronJob` ?  The cli seems to have -output-format which allows you to specify json or yaml output.
