### ISSUE TITLE
Not able to find sample values.yaml

### ISSUE THREAD

**Issue by murarisumit** [FairwindsOps/polaris#185]
I prefer having values.yaml, i could not find one. If there is any, can you guys point me to one. 

TIA

**Comment by murarisumit** [comment]
Got it from helm fetch, but wasn't to find sample file in docs.

**Comment by murarisumit** [comment]
It was all here https://github.com/FairwindsOps/polaris/blob/master/examples/config-full.yaml.

Closing it up. Sorry maintainers for taking your time.

**Comment by endzyme** [comment]
No worries at all. One of our maintainers added https://github.com/FairwindsOps/polaris/pull/186 to see if we can make it easier to find and have more reference docs.
