### ISSUE TITLE
metrics endppoint for dashboard

### ISSUE THREAD

**Issue by rbounds** [FairwindsOps/polaris#187]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to scrape Polaris metrics with Prometheus so I am able to:
 - View scores, number of errors, etc in my unified dashboard.
 - Track changes in scores, errors, warnings, etc over time.
 - Trigger alerts on key metrics.

**Comment by endzyme** [comment]
Thanks for the feature request @rbounds!

To get a little more clarity on `View scores, number of errors, etc in my unified dashboard` -- Is "Unified Dashboard" a product you're using?

**Comment by rbounds** [comment]
Yeah I left it generic sort of by design. Grafana is the most obvious option but Prometheus also offers lots of options via a [remote_write](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage) endpoint. For me the most likely outcome will be signalfx

**Comment by bobby-brennan** [comment]
We discussed this a bit internally - having Prometheus-specific logic built in is a bit out of scope. However, we do expose `/results.json` when running the dashboard, so you could use that to build your own p8s exporter.

Hope that helps!
