### ISSUE TITLE
Split use cases into separate commands/binaries

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/polaris#190]
Currently the same binary runs the dashboard, the webhook, and the CLI audit. This has resulted in a proliferation of flags that is getting out of hand, as well as a very large `main.go`.

Any solution here will likely result in a breaking change, so it's probably for a v1 release.

### Option 1
We could make each of these its own binary. The downside is that there are some flags that are shared (e.g. the path to the polaris configuration), and that we'll have to publish three separate binaries. We may want to abandon homebrew if we go this route.

### Option 2
We could use a [more sophisticated arg parser](https://github.com/spf13/cobra) to split these out into separate commands. E.g. `polaris webhook`, `polaris dashboard --port 3000`, `polaris audit --audit-path ./deploy`

**Comment by sudermanjr** [comment]
I would vote for Option 2. It's a pretty common pattern amongst our projects.
