### ISSUE TITLE
Logic for Capabilities results in duplicate results with different severities

### ISSUE THREAD

**Issue by endzyme** [FairwindsOps/polaris#195]
### Installation Process
Running as binary from laptop.

### Polaris Version
`Polaris version 0.4.0`

### Expected Behavior
The [default configurations](https://github.com/FairwindsOps/polaris/blob/master/examples/config-full.yaml#L56-L65) set the following logic: 

1. Create an error message if `ALL` or `SYS_ADMIN` are set.
2. Create an error message if `ALL` is not dropped
3. Create a warning message if anything except `NONE` is added to the container

This results in the following behavior:
A container with `SYS_ADMIN` is scanned - it gets a message for the initial problem of having `SYS_ADMIN` and an additional message of a warning that `SYS_ADMIN` is added since it's "beyond" just `NONE` allowed in the warning settings.

### Actual Behavior
I would expect only the most severe error to be shown. If `SYS_ADMIN` is on the container or pod, then we should not also show that having `SYS_ADMIN` is an error *and* a warning.

### Steps to Reproduce
Run a report with the default configs and find any `should not be added: SYS_ADMIN` in the `ContainerResults[].Messages[]`.

### Additional Context
N/A

### References
N/A

**Comment by rbren** [comment]
This is fixed with the new schema architecture
