### ISSUE TITLE
Q: Readiness probe always required?

### ISSUE THREAD

**Issue by naseemkullah** [FairwindsOps/polaris#196]
There are workloads that do not expose an API (e.g. a web scraper that gets data and stores it) and thus are not exposed via a service. Polaris still warns that a Readiness Probe should be configured. 

What to do?

**Comment by endzyme** [comment]
Thank you for the question @naseemkullah. We're talking about options for ignores and other features that could help with this. This is a good example of something we need to consider. At the current time we have no feature to ignore readiness or other checks.

**Comment by naseemkullah** [comment]
Sounds good, thanks @endzyme !

**Comment by naseemkullah** [comment]
BTW @endzyme This may seem a little far-fetched but perhaps Polaris could check if the pod is exposed via a service, and if so warn about a readiness probe not being configured, but if there is no service exposing the pod then it will automatically ignore that error.

**Comment by endzyme** [comment]
I like the idea and we'll keep it in mind as we try to brainstorm some ways to accommodate these types of requests. Thanks again!
