### ISSUE TITLE
Don't check for health checks on Jobs/CronJobs

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/polaris#209]
### Polaris Version
latest

### Expected Behavior
CronJobs and Jobs should not fail checks for liveness/readiness probes

### Actual Behavior
Lacking liveness/readiness probes on Jobs/CronJobs causes a decrease in the score

**Comment by ejether** [comment]
Help me understand the logic behind Jobs and CronJobs not needing liveness/readiness probes?

**Comment by davidkarlsen** [comment]
@ejether They run a command until completion. The exit code will tell how it went. Readiness probes are used to let pods enter load-balancing - which cronjob's don't do? Same for liveness - I don't see the need for it - the pod simply runs to completion returning some exit-code.
