### ISSUE TITLE
Support kubeconfig contexts

### ISSUE THREAD

**Issue by bootswithdefer** [FairwindsOps/polaris#210]
Add support for multiple contexts in the kubeconfig.  See: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

**Comment by rbren** [comment]
Hi there!

What's the behavior you're looking for here? If you run `kubectl use-context`, that should run polaris against the desired context.

Or are you looking to specify both `-config` and `-config-context` flags?

**Comment by rbren** [comment]
Closing this - feel free to reopen if you have more details!
