### ISSUE TITLE
No resources checks

### ISSUE THREAD

**Issue by mikhail-matrosov** [FairwindsOps/polaris#222]
### Installation

Kubernetes 1.15.2:
kubectl apply -f [dashboard.yaml](https://github.com/FairwindsOps/polaris/blob/master/deploy/dashboard.yaml)
using basic [config](https://github.com/FairwindsOps/polaris/blob/master/examples/config.yaml)

### Polaris Version

`0.5.1` and `0.5`

### Expected Behavior

Polaris should check if resources are set (cpuLimits, cpuRequests, memoryLimits and memoryRequests)

### Actual Behavior

No checks for resources were conducted (as it is shown in dashboard)

### Additional Context

Version 0.4 works as expected in the same environment and configuration.

**Comment by rbren** [comment]
Thanks for the report! I have a fix in flight in #223 

From what I'm seeing, Polaris _is_ displaying warnings for missing resource requests/limits, but is dropping success messages. This results in a 0 score for resources. Does that sound like what you're seeing?

**Comment by mikhail-matrosov** [comment]
> Polaris is displaying warnings for missing resource requests/limits, but is dropping success messages. This results in a 0 score for resources

Yep, looks like.
`0.5.2` fixes the issue. Thank you so much!
