### ISSUE TITLE
Add priorityClassName check

### ISSUE THREAD

**Issue by mozillazg** [FairwindsOps/polaris#232]
**Is your feature request related to a problem? Please describe.**

Critical add-on pods(such as metrics-server, DNS, controller and all pods in `kube-system`) should set `priorityClassName` to `system-cluster-critical` or `system-node-critical`, use this way to prevent the pod from becoming permanently unavailable.

**Describe the solution you'd like**

Add new check item to check `priorityClassName` config of pod.

**Describe alternatives you've considered**

**Additional context**

* https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Comment by sudermanjr** [comment]
Thanks for the suggestion! We will take a look at this as a possibility. In the meantime you will soon be able to do custom checks using JSONSchema.
