### ISSUE TITLE
examples/config-full.yaml is invalid

### ISSUE THREAD

**Issue by neil-hickey** [FairwindsOps/polaris#237]
### Installation Process
Locally ran `go run main.go ...`
 

### Polaris Version
Master

### Expected Behavior
Run successfully with configuration file

### Actual Behavior
```
go run main.go -config examples/config-full.yaml --dashboard
ERRO[0000] Error parsing config at examples/config-full.yaml: Decoding config failed: error unmarshaling JSON: while decoding JSON: error unmarshaling properties from json: error unmarshaling allOf from json: json: cannot unmarshal object into Go value of type jsonschema.AllOf
exit status 1
```

### Steps to Reproduce
Shown above
The line which causes problems is : https://github.com/FairwindsOps/polaris/blob/master/examples/config-full.yaml#L71

**Comment by rbren** [comment]
Thanks for the report! Fix is up here:

https://github.com/FairwindsOps/polaris/pull/238

**Comment by neil-hickey** [comment]
Great thanks!
