### ISSUE TITLE
Exclude/include namespaces for validating webhook

### ISSUE THREAD

**Issue by kelvin-yue-scmp** [FairwindsOps/polaris#246]
**Is your feature request related to a problem? Please describe.**
We want to use the validating webhook on our cluster but now it would apply to all namespace

**Describe the solution you'd like**
Possible to exclude/include namespaces for validating.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rbren** [comment]
Thanks for reaching out, this is a great feature request!

**Comment by Dimonyga** [comment]
dashboard too
something like:
```polaris dashboard --namespace=example1,example2```

**Comment by mambax** [comment]
Really good feature request. Is it possible in the meantime to exclude like:

```yaml
  exemptions:
    - controllerNames:
        - vacuumrds
      rules:
        - *
```
To exclude a complete controller.
I know it can be done using annotations but its easier to add this than update 50 deployments...
Just curious
