### ISSUE TITLE
Linux binary doesn't handle top level commands as documentation

### ISSUE THREAD

**Issue by hlascelles** [FairwindsOps/polaris#273]
### Installation Process
Downloaded and [untar'd](https://xkcd.com/1168/) the tar and placed binary in path. Mint Linux 19.3

### Polaris Version
```
Polaris version 0.6.0
```

### Expected Behavior
The documenation ([Usage](https://github.com/FairwindsOps/polaris/blob/master/docs/usage.md)) describes running top level commands without dashes like this:
```
polaris version
```

### Actual Behavior
On Linux this just runs `audit`:
```
polaris version
# => Full audit output
```

To run `version` (or `help`/`dashboard` etc...) you need to add dashes:

```
polaris --version
# =>Polaris version 0.6.0
```

I am not sure how it acts on Mac, but I think it may be a build config missing in the Linux binary?

**Comment by rbren** [comment]
Sorry for the confusion. We're in the middle of releasing 1.0, but have been delayed - the current docs are for the upcoming version.

**Comment by mambax** [comment]
@rbren Is there any date expected for 1.0.0? I wait desperately as I celebrate you for the customChecks, even use them already in Dashboard but can not use them with CLI.
When +- would you expect 1.0.0? I will put it then to our backlog to check again...
Love what you guys do but will be able to switch only when 1.0 comes with custom checks with CLI support (need to put it to the CI) 😍

**Comment by rbren** [comment]
Hopefully soon! Ideally it will be in the next two weeks, but we're still finding some minor performance regressions etc that we want to squash first.

If you want, you can use `go run main.go audit` in place of the cli for now

**Comment by mambax** [comment]
@rbren Do you have a release date? I am so badly looking forward to enable our custom check webhook ⚔️ Devs will hate me 😃 

Btw `go run main.go` audit works, yet I don't dare to rollout with the non-master 💯

**Comment by rbren** [comment]
Almost there! https://github.com/FairwindsOps/polaris/pull/300

Just need to merge one more breaking change.

**Comment by rbren** [comment]
1.0.0 released!

**Comment by hlascelles** [comment]
Works perfectly, cheers!
