### ISSUE TITLE
Multi-arch docker support

### ISSUE THREAD

**Issue by NoUseFreak** [FairwindsOps/polaris#284]
**Is your feature request related to a problem? Please describe.**
I am running an arm64 based cluster and would like to run polaris. Any chance you could push multi-arch images?

**Comment by rbren** [comment]
Thanks for the feedback! We'll look into this for the upcoming 1.0 release

**Comment by rbren** [comment]
ARM now supported!

**Comment by rbren** [comment]
Actually I misread this - we're still only pushing AMD images, but we have an ARM binary

**Comment by rbren** [comment]
I've never built multi-arch images, but do you think the following would work?

* build a second ARM binary in the Dockerfile
* copy that ARM binary to our standard alpine distro
* add a flag to the helm chart like `--set architecture=arm`, which would use the ARM binary instead of the AMD binary

**Comment by NoUseFreak** [comment]
Hi,

I've been building locally using the following to support multiarch. I do build the go apps in the container, so they will build using the correct arch. You could lookup the arch to fetch the correct artifact if needed.

```
multiarch:
	docker buildx use $(project)-builder \
		|| (docker buildx create --name $(project)-builder && docker buildx use $(project)-builder)
	docker buildx inspect --bootstrap
	docker buildx build -t $(docker_image):$(version) \
	 	--platform linux/amd64,linux/arm64,linux/arm --push .
	docker buildx rm $(project)-builder
	@echo "Published version $(version)"
```

**Comment by brian-provenzano** [comment]
@NoUseFreak / @rbren  - thanks for looking into getting ARM images (or better multiarch images).  I found this issue when i was trying to get Polaris on my raspberry pi 4 cluster.   I just wanted to drop by and say I have built ARM image that work with RPI4 in case anyone else finds this issue and doesn't want to go through the trouble of building them.

https://hub.docker.com/repository/docker/warpigg/polaris-arm

Once the multi-arch builds are available this is obviously moot :)

**Comment by julweber** [comment]
+1 . I would love to use the official release for my raspberry pi cluster.

**Comment by ankushg** [comment]
+1 - would love this too

**Comment by rbren** [comment]
Happy to say this is now supported!
