### ISSUE TITLE
Ignore 3rd Party CRD

### ISSUE THREAD

**Issue by ScorchedHands** [FairwindsOps/polaris#352]
### Installation Process
Installed via helm chart on kubernetes cluster

### Polaris Version
latest helm release (1.1.0)

### Expected Behavior
functioning dashboard

### Actual Behavior
get "Error fetching Kubernetes resources" message on web
"Cache missed Logging/logging/default-logging again" message in log

### Steps to Reproduce
Install via helm chart, install 3rd party operator (such as "logging.banzaicloud.io")

### Additional Context
It appears that custom CRDs can trip up Polaris, attempted to use "exempt" annotation without success

**Comment by baderbuddy** [comment]
Hello, does it just print errors or does it actually stop Polaris?

It was my assumption that creators of CRDs would add to the View role with their CRDs, apparently this comes up frequently that it doesn't happen. You can definitely grant the Polaris service account access to view that CRD for now, but I believe we have an issue open alreayd to fail more gracefully.

**Comment by ScorchedHands** [comment]
it doesn't crash, but it outputs the errors I notated in the issue. You do not get the web UI, you just get the "error fetching ..." message. I'll look into granting the account access. I just have to remember how to do that.

**Comment by rbren** [comment]
Thanks for the report! [This PR](https://github.com/FairwindsOps/polaris/pull/358) should make us a little more resilient to these cases

**Comment by rbren** [comment]
Should be fixed now - let us know if it's still an issue
