### ISSUE TITLE
Generate report as HTML

### ISSUE THREAD

**Issue by makarek** [FairwindsOps/polaris#363]
Hello

At the beginning I would like to say that tool is realy cool.

It would be even better if I had and ability to generate report as nice HTML.

I'm doing integration of polaris with CI/CD pipeline(generic one) in our company.
In case that some deployment will fail our requirements I want to send him an email with nice report (now I'm sending yaml). So if there is semi technical(Product owner) in email chain, he will se big red error without need to learn how to read json or yaml.

**Comment by rbren** [comment]
Thanks for reaching out!

You might be able to accomplish this by running
```
polaris dashboard --port 3000 --audit-path ./deploy &
curl http://localhost:3000?expand=true > report.html
```

Unfortunately the dashboard makes heavy use of CSS and JavaScript, so the result may not look great in an email.

**Comment by js-timbirkett** [comment]
You can get the raw JSON results at `/results.json` and render it as you like. This could be as simple as a text table in an email.... or, dare I say it, an Excel 🤢 spreadsheet.

**Comment by daaain** [comment]
If anyone wants to save the HTML output with bells and whistles... er, I mean CSS and JS files, you can use `wget` to download the referenced files. It does create a few different directories, so the command below will put all the downloads into `polaris_dashboard` directory.

```
wget --no-verbose --adjust-extension --span-hosts --convert-links --directory-prefix polaris_dashboard --page-requisites http://localhost:3000?expand=true
```
