### ISSUE TITLE
Add prometheus metrics endpoint

### ISSUE THREAD

**Issue by tewing** [FairwindsOps/polaris#390]
**Is your feature request related to a problem? Please describe.**
Polaris should expose a prometheus metrics endpoint.  This would allow prometheus to know the health of polaris and alert if it is unhealthy.  

**Describe the solution you'd like**
http://${POLARIS_POD_IP}/metrics

**Comment by sudermanjr** [comment]
Potential metrics:

- Checks run
- Dashboard refreshes

**Comment by akosveres** [comment]
In addition I'd like to add the power of alerting to this issue, having the polaris dashboard is nice, but we're not going to watch the dashboard every single day, it would be good to have the option of setting up automatic alerts based off the metrics and alert teams owning the services.
