### ISSUE TITLE
API support for polaris checks

### ISSUE THREAD

**Issue by srikar-singam** [FairwindsOps/polaris#418]
**Is your feature request related to a problem? Please describe.**
It is not a best way to include polaris checks in CI/CD tool using binaries.

**Describe the solution you'd like**
An API call based checks. This would not restrict a CI/CD pipeline to use a polaris binary file to check for K8s best practices implementation. Thoughts?

**Comment by rbren** [comment]
Thanks for reaching out!

If you're interested in more of a SaaS-driven way to run Polaris and check best practices, you can check out [Fairwinds Insights](https://insights.fairwinds.com). We have a [CI Feature](https://insights.docs.fairwinds.com/features/continuous-integration/) that will let you run Polaris (and other tooling) to check your infrastructure-as-code.

However, we don't plan to support a free web API for the open source Polaris project.
