### ISSUE TITLE
Error details not found for category reliability

### ISSUE THREAD

**Issue by pgold30** [FairwindsOps/polaris#427]
### Installation Process
 helm 1.2.4

### Polaris Version

helm 1.2.4
```
...
```

### Expected Behavior
 after going to Controller Spec:
 Only one replica is scheduled  
there is no page with recoomendations and we get Error details not found for category reliability

![image](https://user-images.githubusercontent.com/12676941/95466518-b3ad3600-097c-11eb-8531-2757f2c9dfd2.png)
![image](https://user-images.githubusercontent.com/12676941/95466552-be67cb00-097c-11eb-87f6-5c4d7c4ca91a.png)

**Comment by rbren** [comment]
Thanks for the report! Looks like a miscategorization. We'll take a look

**Comment by rbren** [comment]
These links have been updated to go to the docs now.
