### ISSUE TITLE
Use OPA rego checks instead of Polaris built in ones

### ISSUE THREAD

**Issue by akosveres** [FairwindsOps/polaris#429]
**Is your feature request related to a problem? Please describe.**
[Open Policy Agent](https://www.openpolicyagent.org/) is fast becoming the standard of writing policies against infrastructure, be it kubernetes or AWS. The problem we're facing at the moment is that Polaris has it's own way of defining rules. This means we have to duplicate our efforts in writing polaris checks and OPA checks (using [the rego language](https://www.openpolicyagent.org/docs/latest/policy-language/)) which run against our kubernetes cluster and manifest files.

**Describe the solution you'd like**
Polaris checks would be transcribed to rego checks and we'd able to use them with multiple tools (like [conftest](https://github.com/open-policy-agent/conftest) for example).

**Describe alternatives you've considered**
Dropping Polaris and using a solution that does a similar job, we have not found a solution that creates a nice dashboard like Polaris.

**Additional context**
This addition would help drive the adoption of Polaris and it would fit in to the OPA landscape, operations/security teams would only need to learn one new language (rego) and would be able to use it in multiple ways (check terraform code with conftest, run against live AWS environments with fugue, etc.)

**Comment by rbren** [comment]
Hi @akosveres, thanks for the note.

We've considered adding OPA support to Polaris, but have decided it's out of scope for the moment. We see Polaris as a simpler, complementary alternative to OPA.

If you're interested in stronger OPA support, I'd suggest taking a look at [Fairwinds Insights](https://www.fairwinds.com/insights) - it can help you run Polaris, OPA, and other auditing tools in CI, Admission Control, and as an in-cluster report, all behind a nice dashboard.

**Comment by akosveres** [comment]
Thanks so much for the fast reply. I'll close the issue.
