### ISSUE TITLE
Outputting only failed tests

### ISSUE THREAD

**Issue by raeder1986** [FairwindsOps/polaris#433]
Good day! We use polaris v1.2.1 CLI for testing our manifest files in manual mode. The most desirable feature of the application (of course, after analyzing services, ingresses, etc. =)) for us is the ability to display results in the form: score - a list of failed tests. It seems to us that such a conclusion (without a general list of successfully passed tests) greatly simplifies the daily work with the application.

**Comment by daaain** [comment]
I really wanted this, so wrote a little parser snippet using JQ: `jq ".Results[] | {name: .Name, kind: .Kind, results: (.PodResult.Results+.PodResult.ContainerResults[0].Results) | map(select(.Success == false))}"`

This does assume that you don't have more than one container per pod (I don't, so didn't feel like making the parsing setup more complicated by handling a loop).

It also won't give you the score unfortunately as it's not in the JSON output, but if someone feels like implementing it I found the formula: https://github.com/FairwindsOps/polaris/blob/17d19cacffdbfa60ca2fc828b968d62e3779e037/pkg/validator/summary.go#L22

You just need to pipe the output of `polaris audit` into it either directly or using `cat` from a file.
