### ISSUE TITLE
Document prefix support for controller names in exception config

### ISSUE THREAD

**Issue by just1689** [FairwindsOps/polaris#437]
Howdy

Love this tool. Been playing with it and its fantastic!

**Is your feature request related to a problem? Please describe.**
I'm running Longhorn and when it does it's thing it generates controllers with fun names like

- engine-image-ei-3bd16bdf
- instance-manager-e-6babd360
- instance-manager-e-a96b0939
... and so forth.

It occurred to me that it is difficult to setup exceptions to these in a config file because each time the cluster recovers (bounces) new controller will be generated with new names.

**Describe the solution you'd like**
I would like to ask if you would be open to allowing (optionally of course) a wild card character for controller name exceptions.

**Describe alternatives you've considered**
Still thinking about that.

**Additional context**
If you are open to it maybe I can give it a go in a pull request?

Kind regards
Justin

**Comment by just1689** [comment]
Hmm

You might have support for this already without the wildcard character.
```go
			for _, controller := range example.ControllerNames {
				if strings.HasPrefix(controllerName, controller) {
					return false
				}
			}
```

**Comment by just1689** [comment]
Well can confirm it works.

Going to leave this message here for anyone else who wonders. Polaris does support prefix names for controllers.

**Comment by rbren** [comment]
Yup! This is a fairly common case we've run into.

I'm going to reopen this and change the title to update the docs accordingly
