### ISSUE TITLE
Don't show info icon for custom checks

### ISSUE THREAD

**Issue by mambax** [FairwindsOps/polaris#452]
https://polaris.docs.fairwinds.com/checks/

⏬ 

![image](https://user-images.githubusercontent.com/5472171/102482097-fd905780-4062-11eb-9b8b-f4814add10c7.png)

More infos I guess are not needed 😄

**Comment by baderbuddy** [comment]
Where did you find that link at?

**Comment by mambax** [comment]
When you open the polaris dashboard there is a small ❓ mark besides the check. This leads to 404.
![image](https://user-images.githubusercontent.com/5472171/102496269-7ac5c780-4077-11eb-95b9-a4b0faa24d04.png)

**Comment by rbren** [comment]
Thanks for the report!

Definitely something fishy going on. I'm not able to reproduce - how are you running the dashboard? Was it just on the `memory requests should be set` link, or on all the checks?

**Comment by mambax** [comment]
Happy to help. Let me see:

We run it on k8s. With 
```yaml
image:
  repository: quay.io/fairwinds/polaris
  tag: "2.0.1"
  pullPolicy: IfNotPresent
```

We have these checks on:
![image](https://user-images.githubusercontent.com/5472171/102497522-068c2380-4079-11eb-9788-47f13f274ef1.png)

Controller Spec:
 Maintainer Team should be set (maintainer_team, sre) (Custom Check) 404
Pod Spec:
Container: create-log-dir
Container: vault-init-container
Container: autoscheduler
 Memory requests are set works and goes to https://polaris.docs.fairwinds.com/checks/efficiency/ 
 Resource limits are within the required range is broken goes to https://polaris.docs.fairwinds.com/checks/resources
 CPU limits are set works like 2 above
 CPU requests are set same
 Memory limits are set works

Now that you state it I assume that the two custom checks are broken.

What I have to admit is that our config is from 1.1.1 and we want now to update. Also, the resource limit check we have from here https://github.com/FairwindsOps/polaris/blob/master/examples/config-full.yaml

I hope this helps and let me know if we f*** up 😄

**Comment by rbren** [comment]
Oh of course! We shouldn't be putting the `?` on the custom checks since we don't know anything about it 🤦 

I'll rename this bug accordingly
