### ISSUE TITLE
Brew Version !== CLI Version

### ISSUE THREAD

**Issue by mambax** [FairwindsOps/polaris#453]
### Installation Process
Upgraded to latest polaris with `brew`.

### Polaris Version
2.0.1

### Actual & Expected Behavior
```sh
❯ brew upgrade fairwindsops/tap/polaris
Updating Homebrew...
Warning: fairwindsops/tap/polaris 2.0.1 already installed
❯ polaris version
Polaris version:2.0.0
```

### Steps to Reproduce
Type `polaris version` with 2.0.1 installed

### Additional Context
-

**Comment by rbren** [comment]
Should be fixed now with 3.0
