### ISSUE TITLE
Running Polaris Dashboard as Docker container doesn't respond

### ISSUE THREAD

**Issue by daaain** [FairwindsOps/polaris#467]
### Installation Process
Running via Docker image

### Polaris Version
```
3.0
```

Also tried with older versions without much luck.

### Expected Behavior

Being able to use Polaris Dashboard as a Docker container with chart YAML piped in.

### Actual Behavior

Either requests timing out forever or occasionally loading (haven't figured out the pattern yet), but only showing actual chart report for the first load, then displaying empty results for any subsequent page load.

### Steps to Reproduce

First, have some charts to test saved in a file called `chart_test.yaml`. Also, have the Docker daemon running.

```sh
docker network create --driver bridge shared
docker run -it --rm --name polaris_ci_runner_test --net shared --volume /var/run/docker.sock:/var/run/docker.sock --volume ${PWD}:/temp circleci/python:3.7.6 /bin/bash
cd /temp
cat chart_test.yaml | sudo docker run --net shared -d -p 3456:3456 -i --name polaris_dashboard quay.io/fairwinds/polaris:3.0 polaris dashboard --port 3456 --audit-path -
sleep 3
curl http://polaris_dashboard:3456?expand=true > polaris_report.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:05:27 --:--:--     0
```

You can also try to load http://localhost:3456 on the host machine and observe the request hanging.

### Additional Context

In a CI run I'm trying to use the workaround from https://github.com/FairwindsOps/polaris/issues/363, but running Polaris as a Docker container to prevent having to install the binary. Since we're using CircleCI, I can't use volumes so also have to use the stdin pipe solution and also everything is run inside a Docker container already, so Polaris will be run as a sibling container hence the need for communicating via a Docker network.

### References
- #363

**Comment by rbren** [comment]
IIUC you can't pipe to stdin over docker like that.

https://serverfault.com/questions/885765/how-to-send-text-to-stdin-of-docker-container

I'm not sure why the dashboard hangs rather than just showing an empty dash though.

**Comment by rbren** [comment]
🤔 maybe I didn't understand correctly. Still investigating

**Comment by rbren** [comment]
OK figured it out. The problem is that docker is leaving STDIN open, and Polaris waits for an `EOF`. This command works for me:
```
cat test/webhook_cases/failing_test.statefulset.yaml | docker run -p 3456:3456 -i -a STDIN --name polaris
_dashboard quay.io/fairwinds/polaris:3.0 polaris dashboard --port 3456 --audit-path -
```

Note the removal of `-d` and the addition of `-a STDIN`

**Comment by daaain** [comment]
Oh, thank you so much, that worked 🎉

**Comment by daaain** [comment]
Just to circle back to my original post, this is what I ended up doing to make it work in CircleCI (which won't allow Docker volumes and networking on the basic executor):

```
printf "FROM quay.io/fairwinds/polaris:3.0\nUSER root\nWORKDIR /temp\nRUN apk update && apk add --upgrade wget" | docker build -t polaris_dashboard -f - .
cat chart_test.yaml | docker run --name polaris_dashboard -a STDIN -i polaris_dashboard polaris dashboard --port 3456 --audit-path -
sleep 1
docker exec polaris_dashboard wget --no-verbose --adjust-extension --span-hosts --convert-links --page-requisites http://localhost:3456?expand=true
mkdir -p ./polaris_dashboard
docker cp polaris_dashboard:temp/. ./polaris_dashboard
docker kill polaris_dashboard
docker rm polaris_dashboard
```
