### ISSUE TITLE
Ability to extend config defaults, rather than overriding the whole config

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/polaris#500]
From Petar:

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
## Description:
Use case: I am fine with default config and the checks, but would like to change only 1 setting, ie. 
```
memoryRequestsMissing: danger
```

## Observation:
Without passing the --config all the checks from the default configs are validated
```
polaris audit --audit-path . --set-exit-code-on-danger
```
When passing --config with the following output, only one check is validated
```
checks:
  memoryRequestsMissing: danger
```

While this behavior might be fine, I would then expect additional option to override parts of default config, for example adding --extend-config with config that would extend the default config.

This would allow us to always be up to date with the latest default configuration (which we would get by updating to newer polaris version), and then overriding specific parts if needed

Additional use cases might allowing multiple overrides, ie. platform team wants to extend the default polaris config and offer it via Gitlab shared pipeline to the dev teams, but in some cases devs might want to customize some parts, instead of handling exceptions with annotations.

**Describe alternatives you've considered**

**Additional context**

**Comment by rassie** [comment]
I believe this is not completed, just closed by stalebot.
