### ISSUE TITLE
privilegeEscalationAllowed check will fail if allowPrivilegeEscalation is not set

### ISSUE THREAD

**Issue by jessicastenning** [FairwindsOps/polaris#517]
I'm new to Polaris so wanted to check the intention behind this behaviour.

From what I can see in the `privilegeEscalationAllowed.yaml` and its interaction with my cluster, this check fails if `allowPrivilegeEscalation` is not explicitly set to false...

Could you not check this value is _not_ true instead? The `dangerousCapabilities`  check safeguards against `CAP_SYS_ADMIN` capabilities so should mitigate it being set implicitly unless there's another edge case I'm missing?

For context:  I've got some helm charts deployed that don't explicitly set this value so fail this check - I'd rather not make this namespace exempt, so I've written a custom rule that follows the _not_ true logic above.

**Comment by rbren** [comment]
Great question!

We actually fixed this recently. By default, if you don't specify `allowPrivilegeEscalation`, [Kubernetes defaults to `true`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#securitycontext-v1-core). So leaving the field unspecified is the same as setting to `true`.

I'm not entirely sure that dropping `CAP_SYS_ADMIN` obviates the need to set this field to false - I'll need to dig in some more. Regardless, we want each of our policies to work independently, so I think we should leave this one as-is.

If you still want to just check for the explicit `true`, I think your custom check is probably the best way to go.

**Comment by fredgate** [comment]
> We actually fixed this recently. By default, if you don't specify `allowPrivilegeEscalation`, [Kubernetes defaults to `true`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#securitycontext-v1-core). So leaving the field unspecified is the same as setting to `true`.

It is interesting, but I don't in the documentation where it says that the default is true

```
allowPrivilegeEscalation
AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged 2) has CAP_SYS_ADMIN
```
and further
```
Run container in privileged mode. Processes in privileged containers are essentially equivalent to root on the host. Defaults to false.
```
```
capabilities
The  capabilities to add/drop when running containers. Defaults to the  default set of capabilities granted by the container runtime.
```
For example, Docker does not add `CAP_SYS_ADMIN` by default.
