### ISSUE TITLE
New checks for anti-affinity policy or topology spread

### ISSUE THREAD

**Issue by pgold30** [FairwindsOps/polaris#547]
Polaris needs some additional validational checks like Explicit anti-affinity policy  for production deployments.  
Why?
By default, the Kubernetes scheduler uses a bin-packing algorithm to fit as many pods as possible into a cluster. The scheduler prefers a more evenly distributed general node load to app replicas precisely spread across nodes. Therefore, by default, multi-replica is not guaranteed multi-AZ.

Reason to add: Need a way to check if our prod deployments contains soft anti affinity to enable multi az deployments, something to verify that there is something similar to : 
`    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - %appnamehere%
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100`

**Comment by rbren** [comment]
Thanks for the feature request! We've discussed internally, and if we implement a check here we will probably check for the new [topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/)

If you implement anti-affinity as a custom check we'd be happy to add it to our check library

**Comment by sudermanjr** [comment]
Going to tackle this during the CNCF live stream on Nov. 16th
