### ISSUE TITLE
Define exemptions configuration precedence

### ISSUE THREAD

**Issue by renaudhager** [FairwindsOps/polaris#635]
**Describe the solution you'd like**
Hi guys,

I'm testing Polaris and I'm really enjoying it. 

I made some tests, and unless I made a mistake, it looks like that check exemptions defined in annotations override the exemptions defined in the configuration file.

From security perspective I think it's not ideal, since people that can deploy stuff in a namespace can change the annotation of deployment to exempt a particular check that is not exempt in the configmap, where the access to configmap can be restricted to some specific user it's runs in a dedicated namespace.

I think it it would be nice if the exempt defined in the config file have precedence over the one defined in annotations.

**Describe alternatives you've considered**
Another solution (maybe easier to implement) could to have a flag that completely disable exemptions from annotations.

**Comment by rbren** [comment]
Thanks for the PR!

In terms of precedence, exemptions are the _union_ of annotation and config exemptions. So neither has precedence over the other.

I think your solution of allowing users to disable one or the other makes a lot of sense. Thanks again!
