### ISSUE TITLE
Missing resources (Deployment, StatefulSet and DaemonSet) managed by operators in Polaris dashboard

### ISSUE THREAD

**Issue by bygui86** [FairwindsOps/polaris#637]
### Installation Process
Polaris Dashboard runs on Kubernetes provided by Google, deployed by plain YAML manifests using Kustomize.

### Polaris Version
4.1.0

### Expected Behavior
In the report I should see ALL Deployment, StatefulSet and DaemonSet in all namespaces.

### Actual Behavior
I manage Kafka, Cassandra, Fluent-bit, Fluentd, Prometheus and Alertmanager through operators:
- [Strimzi](strimzi.io) for Kafka
- [Instaclustr](https://github.com/instaclustr/cassandra-operator) for Cassandra
- [Logging-operator](https://banzaicloud.com/docs/one-eye/logging-operator/) for Fluent-bit and Fluentd
- [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator) for Prometheus and Alertmanager

In Polaris report I don't see all corresponding StatefulSets (Kafka, Cassandra, Fluentd, Prometheus, Alertmanager) and DaemonSets (Fluent-bit), like in the screenshots below.

![Screenshot 2021-09-24 at 15 06 25](https://user-images.githubusercontent.com/22518997/134680435-bffeed99-1379-474c-ab0e-04f3341e9dab.png)
Here Fluent-bit DaemonSet and Fluentd StatefulSet miss, but Loki StatefulSet is properly analysed

![Screenshot 2021-09-24 at 15 08 35](https://user-images.githubusercontent.com/22518997/134680603-6990b241-58ed-4016-9493-4fb16a78d244.png)
Here Kafka and Zookeeper StatefulSets miss, but Falco DaemonSet is properly analysed

As you can see, Polaris is able to detect other StatefulSets and DaemonSets but not the ones managed by an operator.

### Steps to Reproduce
It's a bit complicated as you have to deploy at least one of the above operators to see the problem :(
The easiest way would be to deploy the prometheus-operator (following instructions [here](https://github.com/prometheus-operator/prometheus-operator#quickstart)) and then deploy Polaris Dashboard.

### Additional Context
Kubernetes version:   v1.19.12-gke.2101

Thanks a lot for your help!

**Comment by rbren** [comment]
Thanks for the report!

Can you share any logs coming out of the dashboard pod? My guess is there's an RBAC issue.

**Comment by bygui86** [comment]
Of course I can!
I thought the same and I checked but nothing.

Here the logs:
```
time="2021-09-24T13:15:13Z" level=info msg="Starting Polaris dashboard server on port 8080"
I0924 13:17:40.721098       1 request.go:665] Waited for 1.002861312s due to client-side throttling, not priority and fairness, request: GET:https://10.4.0.1:443/apis/nodemanagement.gke.io/v1alpha1?timeout=32s
time="2021-09-24T13:17:48Z" level=error msg="Cache missed Logging/logging/logging-components again"
time="2021-09-24T13:17:48Z" level=error msg="Cache missed Logging/logging/logging-components again"
time="2021-09-24T13:17:49Z" level=error msg="Cache missed Logging/logging/logging-components again"
```

**Comment by bygui86** [comment]
@rbren fyi I tried giving `polaris` ServiceAccount explicit access to Deployments, StatefulSet and DaemonSet but nothing :(

**Comment by zebesh** [comment]
Exactly the same problem with https://github.com/tigera/operator

**Comment by glothriel** [comment]
@bygui86 & @zebesh Did you guys solve this somehow?

**Comment by juanvasquezreyes** [comment]
Facing same issue, is there any update?
