### ISSUE TITLE
Check metadataAndNameMismatched not found 

### ISSUE THREAD

**Issue by HariSekhon** [FairwindsOps/polaris#668]
### Installation Process
Docker

### Polaris Version
3.2.1

### Expected Behavior

Expected audit to run

### Actual Behavior

```
WARN[0000] An error occurred validating controller:Check metadataAndNameMismatched not found 
ERRO[0000] Error while running audit on resources: Check metadataAndNameMismatched not found
```

### Steps to Reproduce

```
docker run -ti \
  -v "$PWD/pwd" -v ~/github/k8s:/k8s \
  -v ~/.kube/config:/opt/app/config:ro \
  quay.io/fairwinds/polaris:3.2.1 polaris audit \
    --kubeconfig /opt/app/config \
    --audit-path /pwd \
    --config /k8s/polaris-config.yaml \
    -f pretty --only-show-failed-tests
WARN[0000] An error occurred validating controller:Check metadataAndNameMismatched not found 
ERRO[0000] Error while running audit on resources: Check metadataAndNameMismatched not found
```

The config file I am using is copied from here:

https://raw.githubusercontent.com/FairwindsOps/polaris/master/examples/config.yaml

**Comment by sudermanjr** [comment]
Thanks for the detailed report!

**Comment by sudermanjr** [comment]
Not sure, but it seems that check doesn't exist anymore. I think we should just remove it from the example config.

**Comment by HariSekhon** [comment]
I commented the line out with the `metadataAndNameMismatched` check only to be hit with this error instead, it looks like something more generic is wrong?

```
WARN[0000] An error occurred validating controller:Check missingPodDisruptionBudget not found
ERRO[0000] Error while running audit on resources: Check missingPodDisruptionBudget not found
```

The config I am using is on my public github now here:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/polaris-config.yaml

**Comment by HariSekhon** [comment]
This does seem to be config file related though because if I don't use the sample config file then the scanning actually works, but obviously I want to ignore some select checks like always pull policy which is only important if people are deploying from replacing docker image tags like latest instead of new versioned/hashref tags.

**Comment by HariSekhon** [comment]
Continuing to comment out lines in case it's a couple of the checks that have been removed/renamed, I then get this same error on `pdbDisruptionsIsZero`, and then `pdbDisruptionsIsZero`, but after commenting out all 4 of these then the scan succeeds.

**Comment by sudermanjr** [comment]
I was able to run locally with your configuration, and the example configs. However, I'm running a different version:

```
✗ polaris version
Polaris version:4.0.7
```

 Can you please update to the latest version?

**Comment by HariSekhon** [comment]
Got the same error on 4.0.7 too when I uncommented the config lines.

I've also noticed that if I comment out another check that is working, it doesn't check it by default, so I can't just strip the config down to only the bits I want to override. Perhaps that is something else to improve - leaving all checks enabled if not explicitly disabled?

**Comment by sudermanjr** [comment]
Okay, so this has become really confusing due to the rapid changes. Can you please share the exact configuration that is not working?

**Comment by HariSekhon** [comment]
The config I am using now is this as I had to comment out the 3 not working checks:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/polaris-config.yaml

If I uncomment any of the 3, then I get the errors above about them not being found.

**Comment by sudermanjr** [comment]
Running with 4.0.7 and that exact config with the comments remove works for me.

```
Kubernetes-configs   ⎈ kind-kind  master [±]
▶ polaris audit --config polaris-config.yaml 1>/dev/null
Kubernetes-configs   ⎈ kind-kind  master [±]
▶ echo $?
0


 cat polaris-config.yaml | grep metadata
  metadataAndNameMismatched: ignore  # BUG: not found - https://github.com/FairwindsOps/polaris/issues/668
```

**Comment by HariSekhon** [comment]
That's weird.

Are you running it via a locally installed CLI or via docker like I showed above?

**Comment by sudermanjr** [comment]
Works when I use docker too

```
Kubernetes-configs   ⎈ kind-kind  master [±]
> docker run -i -v ${PWD}:/k8s quay.io/fairwinds/polaris:4.0.7 polaris audit --audit-path /k8s/pdb.yaml --config /k8s/polaris-config.yaml
```

I had to just scan the one file because of the other bug, but this returned zero

**Comment by HariSekhon** [comment]
That could be for 2 reasons:

1. If you're using the latest `polaris-config.yaml` on my github I've commented out the `metadataAndNameMismatched`, `pdbDisruptionsIsZero` and `missingPodDisruptionBudget` lines to work around this issue, so you'd have to uncomment them to reproduce this issue
2. the `pdb.yaml` seems to not hit this issue, but if you change the `--audit-path` to say the `jenkins-server.yaml` then you can reproduce it (after uncommenting the 3 lines in the `polaris-config.yaml` to match the sample config from the master branch):

```
docker run -ti -v $PWD:/k8s -v ~/.kube/config:/opt/app/config:ro  quay.io/fairwinds/polaris:3.2.1 polaris audit --kubeconfig /opt/app/config --audit-path /k8s/jenkins-server.yaml --config /k8s/polaris-config.yaml -f pretty --only-show-failed-tests ; echo $?
WARN[0000] An error occurred validating controller:Check metadataAndNameMismatched not found 
ERRO[0000] Error while running audit on resources: Check metadataAndNameMismatched not found 
1
```

**Comment by sudermanjr** [comment]
1. I removed the commented lines per my previous comment

2. You're still running the outdated version in that example. Please share the output with the newest version of polaris.

**Comment by sudermanjr** [comment]
```
Kubernetes-configs   ⎈ kind-kind  master [±]
✗ docker run -i -v $PWD:/k8s  quay.io/fairwinds/polaris:4.0.7 polaris audit --config /k8s/polaris-config.yaml --only-show-failed-tests -f pretty --audit-path /k8s/jenkins-server.yaml


Polaris audited Path /k8s/jenkins-server.yaml at 2021-11-22T15:47:03Z
    Nodes: 0 | Namespaces: 0 | Controllers: 1
    Final score: 80

  in namespace

StatefulSet jenkins-server in namespace jenkins
  Container jenkins-server
    insecureCapabilities                 😬 Warning
        Security - Container should not have insecure capabilities
    readinessProbeMissing                😬 Warning
        Reliability - Readiness probe should be configured
    notReadOnlyRootFilesystem            😬 Warning
        Security - Filesystem should be read only
    runAsRootAllowed                     😬 Warning
        Security - Should not be allowed to run as root
    privilegeEscalationAllowed           ❌ Danger
        Security - Privilege escalation should not be allowed
        ```
        
 ```
▶ cat polaris-config.yaml | grep metadata
  metadataAndNameMismatched: ignore  # BUG: not found - https://github.com/FairwindsOps/polaris/issues/668
  ```

**Comment by sudermanjr** [comment]
With 4.2.0

```
Kubernetes-configs   ⎈ kind-kind  master [±]
19s ▶ docker run -i -v $PWD:/k8s  quay.io/fairwinds/polaris:4.2.0 polaris audit --config /k8s/polaris-config.yaml --only-show-failed-tests -f pretty --audit-path /k8s/jenkins-server.yaml


Polaris audited Path /k8s/jenkins-server.yaml at 2021-11-22T17:32:13Z
    Nodes: 0 | Namespaces: 0 | Controllers: 1
    Final score: 80



StatefulSet jenkins-serverin namespace jenkins
  Container jenkins-server
    readinessProbeMissing                😬 Warning
        Reliability - Readiness probe should be configured
    runAsRootAllowed                     😬 Warning
        Security - Should not be allowed to run as root
    notReadOnlyRootFilesystem            😬 Warning
        Security - Filesystem should be read only
    privilegeEscalationAllowed           ❌ Danger
        Security - Privilege escalation should not be allowed
    insecureCapabilities                 😬 Warning
        Security - Container should not have insecure capabilities
```

**Comment by HariSekhon** [comment]
Ah yes, that command works when I update the docker image version back up to 4.0.7 - probably there needs to be some doc showing which tests are available in which version or perhaps the sample config file could be commented with which version each check is available from?

That might avoid this question coming up because users would be able to compare their version with the comments in the sample config file.

Ideally if Polaris just ran all available checks without having to list them all in a config file when overriding just one or two, then these sorts of config vs version errors could be mostly avoided? See #672
