### ISSUE TITLE
Run all checks by default if not explicitly listed in a given polaris config file

### ISSUE THREAD

**Issue by HariSekhon** [FairwindsOps/polaris#672]
I've been hitting an issue of mismatched check names in polaris config, as described in #668.

If I try to use a smaller simple config with just the checks I want to override, then the other checks don't to get run at all.

I'd like all checks to be run by default unless explicitly overridden in the config file. This will allow small configs that won't miss checks if they are run against different versions with different checks available.

The alternative would be maintaining multiple configurations for different polaris versions with whatever checks are available in that version and having to try to keep lists of all checks aligned once you start using a config file to override one or two checks - that is impractical.

**Comment by weisdd** [comment]
+1
Currently, we're forced to download the default config from the repo each time a pipeline runs and then merge the config with our overrides with the help of `yq`. It should have been much easier :)
