### ISSUE TITLE
GitHub Actions - use pre-built docker image instead of building go binary in each workflow?

### ISSUE THREAD

**Issue by HariSekhon** [FairwindsOps/polaris#680]
I'm trying out running Polaris in GitHub Actions following the doc below and am finding that it is building the go binary in each workflow run.

https://polaris.docs.fairwinds.com/infrastructure-as-code/#running-in-a-ci-pipeline

Could we instead just pull the quay.io/fairwinds/polaris docker image and run the audit step inside that?

**Comment by sudermanjr** [comment]
Sure! We would be happy to review a PR for that change. We don't have a ton of github actions experience, so we rely on the community for that support.
