### ISSUE TITLE
Filter by namespace in CLI

### ISSUE THREAD

**Issue by bkrein-vertex** [FairwindsOps/polaris#741]
Related to the improvement added for #123 - it'd be nice to be able to do this from the CLI as well without having to manually parse JSON.  

Essentially I'm looking for something like this: 

```shell
polaris audit --namespace foo
```

And have it generate the report for *JUST* the `foo` namespace (same as what happens when you filter namespaces in the dashboard).

**Comment by sudermanjr** [comment]
@bkrein-vertex Thanks for the request! This seems like a great idea, and something that shouldn't be too difficult to implement.
