### ISSUE TITLE
Filter only specific status types in CLI

### ISSUE THREAD

**Issue by bkrein-vertex** [FairwindsOps/polaris#754]
It'd be nice to be able to filter the output of the `polaris audit` CLI command to only display specific test results.  In other words I'd like to be able to only show tests that fail with a "Danger" status (ignoring "Warning", etc.).  

Perhaps adding flags like this?

- `--only-show-danger`
- `--only-show-warning`

Or something more complicated like this?

- `--show "Danger, Warning"`

Or a reusable flag?

- `--show Danger --show Warning`

**Comment by sudermanjr** [comment]
Right now we have the `--only-show-failed-tests` which will get you part of the way there

**Comment by sudermanjr** [comment]
I marked this as a an enhancement. If someone is willing to contribute, we would be happy to review!

**Comment by jslivka** [comment]
This should now be supported with the introduction of https://github.com/FairwindsOps/polaris/pull/969
