### ISSUE TITLE
Emojis are not fully stripped in pretty format with no colors

### ISSUE THREAD

**Issue by weisdd** [FairwindsOps/polaris#764]
### What happened?

Audit in pretty format with no colors does not properly strip emojis leaving some broken binary symbols:
```shell
$ polaris audit --audit-path /tmp/1.yaml -f pretty --color=false
[...]
Deployment app
    deploymentMissingReplicas            �� Success
        Reliability - Multiple replicas are scheduled
```

### What did you expect to happen?

No special characters should be present next to the status field.

### How can we reproduce this?

`polaris audit --audit-path <PATH> -f pretty --color=false`

### Version

6.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rbren** [comment]
Thanks for the report! We'll take a look
