### ISSUE TITLE
Be able to merge custom configuration with default one

### ISSUE THREAD

**Issue by Flauschbaellchen** [FairwindsOps/polaris#770]
**Is your feature request related to a problem? Please describe.**
The only change to the default configuration I want to do is to disable the `tagNotSpecified` check.
The configuration file in question would be like:
```
checks:
  tagNotSpecified: ignore
```
In case I create my own configuration file and specify it via `--config`, all checks will be disabled.

**Describe the solution you'd like**
I'd like to be able to use the default configuration provided by the project.
In this case, the project owner and the community can provide sensible defaults.
By merging the default configuration with my additions I'd be able to further adjust the configuration to the specific needs of my project.

**Describe alternatives you've considered**
I could download the default configuration file from the example directory and adjust it accordingly.
However, I would miss out further updates to it and would need to manually check it from time to time.

**Additional context**
Polaris version: 5.0.0

**Comment by sudermanjr** [comment]
I love this idea.

**Comment by Flauschbaellchen** [comment]
@sudermanjr Has this really been implemented? I do not see anything within the changelogs or documentation and no PR or commit has been reverenced here.

**Comment by Flauschbaellchen** [comment]
@rbren This issue is unsolved but has been closed automatically by the github-bot. Can you re-open it? :bow:

**Comment by Flauschbaellchen** [comment]
@rbren Might I kindly remind you? :bow:
