### ISSUE TITLE
Deprecated set-output in GitHub Actions

### ISSUE THREAD

**Issue by ad-m-ss** [FairwindsOps/polaris#860]
### What happened?

In https://github.com/FairwindsOps/polaris/blob/master/.github/actions/setup-polaris/get_polaris.sh#L20 we use deprecated ```set-output``` syntax. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ . 

### What did you expect to happen?

 We should migrate to new syntax:
 
 ```
 echo "{name}={value}" >> $GITHUB_OUTPUT
```
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter .

### How can we reproduce this?

Not applicable (yet)

### Version

7.1.5

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mggude** [comment]
Hello! Thanks for the feedback. We do not use GitHub actions ourselves, and the action for Polaris was a community contribution. We would be happy to approve a PR to fix this if someone would like to open one. Thanks again!
