### ISSUE TITLE
Doc navigation breaks if initial url isn't root

### ISSUE THREAD

**Issue by fredzach** [FairwindsOps/polaris#861]
### What happened?

Cannot navigate the documentation properly unless I explicitly open sections in new tabs.

### What did you expect to happen?

Navigation to work normally.

### How can we reproduce this?

1. Go to e.g. https://polaris.docs.fairwinds.com/infrastructure-as-code/ directly (not navigating from root /)
2. Click `Configuration`. Your window url will change accordingly, but the page is not reloading.
3. Click a sub-section of IaC, e.g. `Install the CLI` and you're directed properly.

Seems whatever section you initially load, you're locked into. If you instead browse to https://polaris.docs.fairwinds.com/, you can navigate properly.

Cannot replicate locally running the vuepress app, likely related to the doc webserver settings.

MacBook m1, Chrome v105.0.5195.125.

### Version

main

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Being a doc site bug and not a tool bug, I'm not sure if the place is right. But it does impede you in adopting Polaris.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/7817071/195840971-e35defb1-9f7c-48a2-9b85-9bb7613afbb0.png">

**Comment by mggude** [comment]
Hello! Thanks for pointing this out. We will take care of this, thanks again!
