### ISSUE TITLE
Namespaced audit fails finding resources

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/polaris#878]
### What happened?

polaris audit on a specific namespace failed

### What did you expect to happen?

the audit to succeed

### How can we reproduce this?

```
home/polaris-demo   ☸ kind-kind
✗ polaris audit --format pretty --namespace demo
INFO[0000] Loading nodes
INFO[0000] Loading namespaces
INFO[0000] Loading pods
INFO[0000] Setting up restmapper
INFO[0000] Loading rbac.authorization.k8s.io/ClusterRole
WARN[0000] Error retrieving parent object API v1 and Kind clusterroles because of error: the server could
not find the requested resource
ERRO[0000] Error fetching Kubernetes resources the server could not find the requested resource
```

### Version

Polaris version:7.2.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arnaud1000i** [comment]
This bug is still occurring, can this issue be re-opened?
