### ISSUE TITLE
Issue when running polaris as a Docker container

### ISSUE THREAD

**Issue by GuillermoContrerasP** [FairwindsOps/polaris#887]
### What happened?

When I run polaris as a docker container to audit a couple of K8s manifest, I receive no relevant output:

`docker run -t -i --rm --init -v $(pwd):/data quay.io/fairwinds/polaris polaris audit --audit-path examples/cassandra/ --format=pretty`
Polaris audited Path examples/cassandra/ at 2022-12-05T23:38:30Z
    Nodes: 0 | Namespaces: 0 | Controllers: 0
    Final score: 100

### What did you expect to happen?

I was expecting to get the exact same result as a local run with the CLI:

`polaris audit --audit-path examples/cassandra/ --format=pretty`
Polaris audited Path examples/cassandra/ at 2022-12-05T23:36:31Z
    Nodes: 0 | Namespaces: 0 | Controllers: 1
    Final score: 78

Service cassandra

StatefulSet cassandra
    hostIPCSet                           🎉 Success
        Security - Host IPC is not configured
    hostNetworkSet                       🎉 Success
        Security - Host network is not configured
    hostPIDSet                           🎉 Success
        Security - Host PID is not configured
  Container cassandra
    insecureCapabilities                 😬 Warning
        Security - Container should not have insecure capabilities
    livenessProbeMissing                 😬 Warning
        Reliability - Liveness probe should be configured
    memoryLimitsMissing                  🎉 Success
        Efficiency - Memory limits are set
    tagNotSpecified                      🎉 Success
        Reliability - Image tag is specified
    dangerousCapabilities                🎉 Success
        Security - Container does not have any dangerous capabilities
    pullPolicyNotAlways                  🎉 Success
        Reliability - Image pull policy is "Always"
    runAsPrivileged                      🎉 Success
        Security - Not running as privileged
    runAsRootAllowed                     ❌ Danger
        Security - Should not be allowed to run as root
    cpuRequestsMissing                   🎉 Success
        Efficiency - CPU requests are set
    hostPortSet                          🎉 Success
        Security - Host port is not configured
    memoryRequestsMissing                🎉 Success
        Efficiency - Memory requests are set
    notReadOnlyRootFilesystem            😬 Warning
        Security - Filesystem should be read only
    readinessProbeMissing                🎉 Success
        Reliability - Readiness probe is configured
    cpuLimitsMissing                     🎉 Success
        Efficiency - CPU limits are set
    privilegeEscalationAllowed           ❌ Danger
        Security - Privilege escalation should not be allowed

StorageClass fast

### How can we reproduce this?

`docker run -t -i --rm --init -v $(pwd):/data quay.io/fairwinds/polaris polaris audit --audit-path examples/cassandra/ --format=pretty`

The files that I tested with can be downloaded from the public kubernetes repository: https://github.com/kubernetes/examples/tree/master/cassandra

### Version

Polaris version:7.2.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
It looks like maybe your command is incorrect. The audit-path should be `/data/....`

```
docker run -t -i --rm --init -v $(pwd):/data quay.io/fairwinds/polaris polaris audit --audit-path /data/examples/cassandra/ --format=pretty
```

**Comment by GuillermoContrerasP** [comment]
I tried that command, but that didn't work either:

`docker run -t -i --rm --init -v $(pwd):/data quay.io/fairwinds/polaris polaris audit --audit-path /data/examples/cassandra/ --log-level trace
{
  "PolarisOutputVersion": "1.0",
  "AuditTime": "2022-12-07T00:47:25Z",
  "SourceType": "Path",
  "SourceName": "/data/examples/cassandra/",
  "DisplayName": "/data/examples/cassandra/",
  "ClusterInfo": {
    "Version": "unknown",
    "Nodes": 0,
    "Pods": 0,
    "Namespaces": 0,
    "Controllers": 0
  },
  "Results": [],
  "Score": 100`

**Comment by sudermanjr** [comment]
This worked for me. I had to be mindful of the directory that I was currently in `$(pwd)`. When sitting in the cassandra directory, the audit-files path becomes `/data/`

```
examples/cassandra    master
✗ docker run -t -i --rm --init -v $(pwd):/data quay.io/fairwinds/polaris polaris audit --audit-path /data/ --format=pretty
Unable to find image 'quay.io/fairwinds/polaris:latest' locally
latest: Pulling from fairwinds/polaris
ca7dd9ec2225: Pull complete

Digest: sha256:8bb71348ed0c74392b643784e7629880def4b2f13b136633056b3208ba8c1d66
Status: Downloaded newer image for quay.io/fairwinds/polaris:latest
Polaris audited Path /data/ at 2022-12-07T15:49:32Z
    Nodes: 0 | Namespaces: 0 | Controllers: 1
    ```

**Comment by GuillermoContrerasP** [comment]
I was able to get that working using that option:

`docker run -t -i --rm --init -v $(pwd):/data quay.io/fairwinds/polaris polaris audit --audit-path /data/ --format=pretty`
Polaris audited Path /data/ at 2022-12-07T16:51:48Z
    Nodes: 0 | Namespaces: 0 | Controllers: 1
    Final score: 77

StatefulSet cassandra
    hostIPCSet                           🎉 Success
        Security - Host IPC is not configured
    hostNetworkSet                       🎉 Success
        Security - Host network is not configured
    hostPIDSet                           🎉 Success
        Security - Host PID is not configured
  Container cassandra
    cpuLimitsMissing                     🎉 Success
        Efficiency - CPU limits are set
    insecureCapabilities                 😬 Warning
        Security - Container should not have insecure capabilities
    livenessProbeMissing                 😬 Warning
        Reliability - Liveness probe should be configured
    notReadOnlyRootFilesystem            😬 Warning
        Security - Filesystem should be read only
    readinessProbeMissing                🎉 Success
        Reliability - Readiness probe is configured
    runAsRootAllowed                     ❌ Danger
        Security - Should not be allowed to run as root
    tagNotSpecified                      🎉 Success
        Reliability - Image tag is specified
    privilegeEscalationAllowed           ❌ Danger
        Security - Privilege escalation should not be allowed
    cpuRequestsMissing                   🎉 Success
        Efficiency - CPU requests are set
    hostPortSet                          🎉 Success
        Security - Host port is not configured
    linuxHardening                       😬 Warning
        Security - Use one of AppArmor, Seccomp, SELinux, or dropping Linux Capabilities to restrict containers using unwanted privileges
    memoryRequestsMissing                🎉 Success
        Efficiency - Memory requests are set
    sensitiveContainerEnvVar             🎉 Success
        Security - The container does not set potentially sensitive environment variables
    dangerousCapabilities                🎉 Success
        Security - Container does not have any dangerous capabilities
    memoryLimitsMissing                  🎉 Success
        Efficiency - Memory limits are set
    pullPolicyNotAlways                  🎉 Success
        Reliability - Image pull policy is "Always"
    runAsPrivileged                      🎉 Success
        Security - Not running as privileged

StorageClass fast

Service cassandra

Thanks a lot for the help. Cheers
