### ISSUE TITLE
[chart] proposal: nodeselector should be set to linux by default

### ISSUE THREAD

**Issue by mac2000** [FairwindsOps/polaris#892]
if the cluster has a windows node then there is a chance that Polaris won't start because of lack windows images 🤷‍♂️

<img width="658" alt="image" src="https://user-images.githubusercontent.com/88868/207433951-1c541293-5809-4a75-8d8a-798d5ffb16ae.png">

workaround: `kubectl -n polaris edit deployment polaris-dashboard` and add

```yaml
nodeSelector:
  kubernetes.io/os: linux
```

**Comment by sudermanjr** [comment]
How are you installing the Polaris dashboard?

**Comment by mac2000** [comment]
@sudermanjr by blindly copy-pasting commands from the getting started [guide](https://polaris.docs.fairwinds.com/dashboard/#installation) 🙃

```bash
helm repo add fairwinds-stable https://charts.fairwinds.com/stable
helm upgrade --install polaris fairwinds-stable/polaris --namespace polaris --create-namespace
```

PS: Yes, I understand that it is probably configurable via some value, and I bed I can find it, but shouldn't it be set to default if it won't ever work on the windows node

**Comment by sudermanjr** [comment]
Gotcha. If you wanted to open a PR up on the chart at https://github.com/fairwindsops/charts I think we would be happy to accept that change.
