### ISSUE TITLE
cpuLimits check should not be enabled by default

### ISSUE THREAD

**Issue by michalschott** [FairwindsOps/polaris#912]
### What happened?

There were many discussions around should cpu limits be set or not. AFAIK current state is that with CPU limit sets there might be timeframes where CPU is totally idle - where this reserved CPU time could be used elsewhere.

There might be situations where this is desired / set on purpose thus I'm proposing to disable this check in default configuration.

### What did you expect to happen?

cpuLimits check should not be enabled by default

### How can we reproduce this?

N/A

### Version

7.3.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
There has been a large amount of discussion about this topic, however we still feel that CPU limits are the only correct way to prevent noisy neighbors and pods that take over entire nodes. For the time being, I personally prefer to leave them in place.

**Comment by rbren** [comment]
Agreed--this has come up before, and we've always landed in the "it's still better to set them" camp.

I'm going to close this for now @michalschott, but if you want to send along any evidence/resources I'm happy to take a look. It's possible that the consensus has changed since last I looked.

**Comment by rbren** [comment]
(also, seems like you're aware, but for posterity: you can turn checks on and off via a custom configuration)

**Comment by michalschott** [comment]
https://youtu.be/NqtfDy_KAqg

This is very good talk from KubeCon 2022 witch explains a lot

**Comment by sudermanjr** [comment]
Seems to me that explains much more about why you shouldn't scale on CPU as a metric (which I 100% agree with), and not so much on CPU limits. Great info about thinking in time vs cores though, which definitely leads to a lot of confusion.

It's a very complex topic, and I definitely think that everyone should evaluate their workloads and and their settings related to those workloads. Polaris is our experience of best practices that work for us, but that will not apply perfectly to every cluster/workload/operator. 

Thanks for the info, and the suggestion!

**Comment by michalschott** [comment]
If you're suggesting that having possible cpu throttling and a waste of cpu time is a good practice, I disagree. Linux cpu subsystem/layer takes really good care about assigning cpu time to processes, let it do what it is supposed to do in a good manner.
