### ISSUE TITLE
metadataAndNameMismatched

### ISSUE THREAD

**Issue by vl-kp** [FairwindsOps/polaris#972]
### What happened?

metadataAndNameMismatched
Fails when label app.kubernetes.io/name and metadata.name mismatch

But from https://kubernetes.io/docs/reference/labels-annotations-taints/ the metadata name should match with app.kubernetes.io/instance

```
app.kubernetes.io/instance
Type: Label

Example: app.kubernetes.io/instance: "mysql-abcxzy"
```

```
app.kubernetes.io/name
Type: Label

Example: app.kubernetes.io/name: "mysql"
```

### What did you expect to happen?

Remove the rule or update to match `app.kubernetes.io/instance`

### How can we reproduce this?

when label app.kubernetes.io/name and metadata.name mismatch

### Version

7.4.2

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Thanks, I think we should probably change the check rather than removing it. @rbren
