### ISSUE TITLE
Support `--skip-tests` for `helm template`

### ISSUE THREAD

**Issue by mikutas** [FairwindsOps/polaris#985]
**Is your feature request related to a problem? Please describe.**

We use `polaris audit` with Helm charts in our CI.
We define exemptions for tests/ directory because there is no need for us to audit tests.
If there is a way to input `--skip-tests` when Polaris executes `helm template` internally, we can remove the troublesome exemptions.

**Describe the solution you'd like**

It may be new `--helm-skip-tests` flag of `audit` command

**Describe alternatives you've considered**

**Additional context**

**Comment by sudermanjr** [comment]
Seems like a great idea.
