### ISSUE TITLE
privilegeEscalationAllowed forces label to be set

### ISSUE THREAD

**Issue by sempex** [FairwindsOps/polaris#997]
### What happened?

I want the test to fail only when the following configuration is detected:
```yaml
securityContext:
  allowPrivilegeEscalation: true
```
Currently, the test does fail when this configuration is present. However, I don't want it to fail when nothing is specified. Sometimes, it's not straightforward to specify this property, especially when using Helm Charts.

It's important to note that when the allowPrivilegeEscalation field is not explicitly set in the configuration, the default value is false. This default behavior is outlined in the Kubernetes documentation [here](https://github.com/kubernetes/design-proposals-archive/blob/main/auth/no-new-privs.md#changes-of-securitycontext-objects).

Therefore, the test should not require the property to be set, but rather, it should only fail when the property is explicitly set to true.

### What did you expect to happen?

I anticipate that when no securityContext configuration is provided, this test should pass. This expected outcome is due to the default value of `allowPrivilegeEscalation` being set to `false`.

### How can we reproduce this?

Create a deployment without specifying any `securityContext` settings, and then inspect the Polaris Dashboard. You will observe that the `privilegeEscalationAllowed` check fails. However, it's essential to note that, from Kubernetes' perspective, `allowPrivilegeEscalation` is indeed disabled by default in this scenario.

### Version

5.7.3

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rbren** [comment]
@sudermanjr should we make the check more sophisticated to ensure that CAP_SYS_ADMIN and privileged are not set? That's doable
