### ISSUE TITLE
Bug in missingPodDisruptionBudget check

### ISSUE THREAD

**Issue by jan-pieter** [FairwindsOps/polaris#999]
I think there is a bug in the missingPodDisruptionBudget check when there are multiple labels in the `matchLabels` selector. Kubernetes combines these with AND and it seems the missingPodDisruptionBudget check combines them with OR:

https://github.com/FairwindsOps/polaris/blob/97687761a78388a3d00ad875601a19f48a0999ae/checks/missingPodDisruptionBudget.yaml#L32

Shouldn't that be `allOf` instead?

I noticed this when I was applying a PodDisruptionBudget to a deployment using Kustomize in combination with `commonLabels`. That adds those labels to the `matchLabels` as well. Now Polaris thinks it applies to all my deployments (because they have at least one label in common).

**Comment by sudermanjr** [comment]
In the future, please use the `Bug Report` [type of issue](https://github.com/FairwindsOps/polaris/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug.yaml) - This ensures that the proper labels get added for us to track this issue. Thanks!

**Comment by jan-pieter** [comment]
Ah sorry, I created this issue based on the code (`Reference in new issue`) which apparently circumvents the use of templates :see_no_evil:

**Comment by rbren** [comment]
I think you're right! Fix is here: https://github.com/FairwindsOps/polaris/pull/1000

I will add a test as well
